= Dec '23 PAIWeb #1 Meetup

This repository contains the materials used during the Dec '23 PAIWeb #1 Meetup event.

We mostly did live-coding together and explored the LangChain Expression Language (LCEL), as well as a simple implementation of Retrieval Augmented Generation (RAG).

The code was discussed during the https://www.meetup.com/arnhem-paiwed-the-friendly-python-ai-webdev-meetup/events/297254389/[Dec '23 PAIWeb #1 Event] of the https://www.meetup.com/arnhem-paiwed-the-friendly-python-ai-webdev-meetup/[Arnhem PAIWeb Meetup].

== Local Setup

To run the application locally, follow these steps:

. Clone this repository to the desired local folder
. Ensure you have a suitable Python version (3.10 or higher) installed and accessible on your path (you can verify this via `python -V`).
** Can use Conda/Miniforge or https://github.com/pyenv/pyenv[PyEnv] to bootstrap Python, if needed.

. Create a virtual environment and activate it
** `python -m venv venv --copies`
** `python source venv/bin/activate`
** `which pip`
*** Sanity check -> Should display path to new venv

. Install the dependencies via `pip install -r requirements.in`.
. Ensure you have access to an OpenAI API key.
. Copy the `.env.template` file to `.env` and fill in your OpenAI API key
. Start a Jupyter Server (via `jupyter lab` or use PyCharm Professional or VSCode to open the Jupyter Notebook file)
. Explore the code in `lcel.ipynb`
. Have fun and write some Python :-)

== Support

If you should run into any issues, or would like to discuss the code and topics covered in the session with fellow technology enthusiasts, you can do so in the https://chat.paiweb.dev[PAIWeb Community Chat].

If you aren't part of the Arnhem PAIWeb Meetup Community yet and still somehow find your way to this repo and need support, you can reach out via `arno at paiweb.dev`.